name: wefix
description: A new Flutter project.
publish_to: "none"

version: 1.1.8+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  carousel_slider: ^5.1.1

  flutter:
    sdk: flutter
  # Lnaguage
  flutter_localizations:
    sdk: flutter
  # Rating
  flutter_rating_stars: ^1.1.0
  # SVG
  flutter_svg: ^2.2.1
  # Date
  intl: ^0.20.2
  # Phone Number
  intl_phone_number_input: ^0.7.4
  image: ^4.1.7
  # Animation Icon
  get_it: ^7.7.0

  # Indicator
  # smooth_page_indicator: ^1.1.0
  # Permission
  awesome_notifications: ^0.10.1

  # Drop Down
  dropdown_textfield: ^1.2.0
  # Firebase
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  bot_toast: ^4.1.3
  # Check Network in Application
  connectivity_plus: ^6.1.5
  # App Prvider
  provider: ^6.1.5+1
  # Shared Preferences
  shared_preferences: ^2.5.3
  # Cach Netwok Image
  cached_network_image: ^3.3.1
  # Loading Shimmer
  shimmer: ^3.0.0
  # Google Map
  google_maps_flutter: ^2.2.4
  flutter_google_places: ^0.3.0
  # flutter_paytabs_bridge: ^2.6.1
  geocoding: ^4.0.0
  geolocator: ^9.0.2
  # location: ^4.4.0
  google_api_headers: ^1.5.0+1
  # google_maps_webservice: ^0.0.20-nullsafety.5
  # fluttertoast: ^8.2.5
  # flutter_paypal_checkout: ^1.0.1
  image_picker: ^1.2.0
  # Html Widget
  flutter_widget_from_html: ^0.17.1
  # Icon Luncher
  flutter_launcher_icons: ^0.14.4
  # readmore: ^3.0.0
  # flutter_facebook_auth: ^6.0.4
  # speech_to_text: ^6.6.0
  url_launcher: ^6.3.2
  # flutter_staggered_grid_view: ^0.7.0
  google_sign_in: ^5.0.0
  firebase_auth: ^6.0.2
  pin_code_fields: ^8.0.1
  http: ^1.5.0
  local_auth: ^2.3.0
  flutter_rating_bar: ^4.0.1
  convex_bottom_bar: ^3.2.0
  table_calendar: ^3.2.0
  file_picker: ^10.3.2
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.1
  record: ^3.0.0
  video_player: ^2.10.0
  audioplayers: ^6.5.1
  open_file: ^3.5.10
  signalr_netcore: ^1.4.4
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  url_launcher_ios: ^6.3.4
  # google_sign_in: ^7.1.1
  # showcaseview: ^4.0.1

  webview_flutter: ^4.13.0
  sms_autofill: ^2.4.1
  # tutorial_coach_mark: ^1.2.9

  tutorial_coach_mark: ^1.3.1
  # flutter_widget_from_html: ^0.15.3
  # jitsi_meet_flutter_sdk: ^10.0.0
  change_app_package_name: ^1.5.0
  percent_indicator: ^4.2.5
  simple_circular_progress_bar: ^1.0.2

dependency_overrides:
  http: ^0.13.1

flutter_icons:
  android: launcher_icon
  ios: true
  remove_alpha_ios: true
  image_path: assets/image/icon_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/video/wefix_logo_motion.mp4
    - assets/video/mixkit-correct-answer-tone-2870.wav

  fonts:
    - family: Poppins
      fonts:
        # - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/JANNALT-REGULAR (1).TTF
